const thanks = ['Thank you for taking the time to speak with us today',
 'Thank you for sharing your valuable insights with us.', 
 'Thank you for sharing your expertise with us.',
 'Thank you for sharing your knowledge with us.',
 'Thank you for sharing your wisdom with us.',
 'Thank you for sharing your experience with us.',
 'Thank you for sharing your stories with us.',
 ' Thank you for sharing your time with us',
 'Thank you for sharing your knowledge and expertise with us',
 ' Thank you for your patience in answering our questions.',
 'Thank you for providing us with valuable information.',
 'Thank you for your insights and observations.',
 'Thank you for making your presentation interesting and enjoyable.',
]
    
